MODULE_NAME := libc

C_SOURCES := \
	src/string/strlen.c \
	src/string/strchr.c \
	src/string/memchr.c \
	src/string/memset.c \
	src/string/memcpy.c \
	src/stdio/sprintf.c \
	src/math/log10.c \
	src/math/pow.c \
	src/math/util.c

include ../make/build_module.mk
